### PR TITLE
Support the corejs runtime packages

### PR DESCRIPTION
**Pull request by tilgovi**

### CODE REVIEW

**Comment by tilgovi** [comment]
Maybe not terribly effective. The relative imports between the modules within the runtime still fail under ESM.

**Comment by tilgovi** [comment]
I'll close this. It should not be long before babel resolves this upstream.

**Comment by jaydenseric** [comment]
Sorry I have not had the time to review this; I normally have a few days off a week for open source but lately with a few work deadlines that has not been the case.

> It should not be long before babel resolves this upstream.

I'm curious what makes you say of this? https://github.com/babel/babel/issues/8462 is not going to be fixed until Babel v8, which could be a long way off.

**Comment by tilgovi** [comment]
> Sorry I have not had the time to review this

No worries at all.

> I'm curious what makes you say of this? babel/babel#8462 is not going to be fixed until Babel v8, which could be a long way off.

Baseless optimism :grin:.

I can re-open this, if you like. I was initially discouraged due to the relative imports that I mentioned, but it's still possible to build an ESM package using the CJS runtime helpers (`useESModules: false`).

**Comment by tilgovi** [comment]
Closing this as babel/babel#8462 is fixed in @babel/runtime@7.12.0.

**Pull request closed without merging**
