### PR TITLE
Add /index.js to @babel/runtime/regenerator

### PR DESCRIPTION
**Pull request by ArnoSaine**
Hi! Thanks for this workaround plugin. I noticed that imports from `@babel/runtime/regenerator` would also need the file extensions. Unlike `runtime/helpers`, there's only `index.js`.

### CODE REVIEW

**Review by jaydenseric — CHANGES_REQUESTED** [review]
Glad you're also finding this package helpful :)

I've merged in updated dev dependencies from `master` branch.

Could you please fix the lint errors? Then I'll take a closer look. If you don't have ESLint setup in your editor, you can run `npm test` to see the errors.

**Comment by ArnoSaine** [comment]
My bad :) I added the missing tests too.

**Comment by jaydenseric** [comment]
Thanks for your work and patience waiting on the review :)

I usually have mondays and tuesdays to work on open source, and also sometimes on the weekend if I have time. I ended up jumping down a very deep rabbit-hole early this week attempting to replace the [`doctrine`](https://github.com/eslint/doctrine) dependency, which has been [abandoned by ESLint](https://eslint.org/blog/2018/11/jsdoc-end-of-life), in [`jsdoc-md`](https://github.com/jaydenseric/jsdoc-md) (what I use to document all my packages) and it turned out to be very complicated. I was working until tuesday midnight and ran out of time.

I'll get to this PR and a few other important ones as soon as I can, over the next few days :)

**Comment by jaydenseric** [comment]
Keep in mind that while you are waiting for your PR to be reviewed, merged and released, you can temporarily install your PR in your project as Git dependency:

```
npm install github:ArnoSaine/babel-plugin-transform-runtime-file-extensions#patch-1 --save-dev
```

I always make sure my packages have the right `prepare`, etc. scripts to support this.

**Review by jaydenseric — APPROVED** [review]
Thanks for your work 🙌

**Comment by jaydenseric** [comment]
This has been published in [v2.0.0](https://github.com/jaydenseric/babel-plugin-transform-runtime-file-extensions/releases/tag/v2.0.0) 🚀

**Comment by ArnoSaine** [comment]
Thank you Jayden for the review, merge and all of your hard work.

You have high quality packages! I'll take a closer look at your build scripts and jsdoc-md 🙂

**Pull request merged**
